<?php require './templates/header.phtml'; ?>
<section>
	<table border="0">
		<thead>
		<tr>
			<th colspan="2"><?php echo get('filename')?></th>
		</tr>
		</thead>
		<tbody>
		<?php for($i = 0, $c = count($source); $i < $c; $i++): ?>
			<tr>
				<td id="<?php echo $i + 1 ?>"><?php echo $i + 1 ?></td>
				<td><?php echo empty($source[$i]) ? '&nbsp;' : $source[$i]; ?></td>
			</tr>
		<?php endfor;?>
		</tbody>
	</table>
</section>
<?php require './templates/footer.phtml'; ?>