<?php require './templates/header.phtml'; ?>
    <section class="file">
        <div>
            <h2><?php echo get('filename') ?></h2>
        </div>

        <table>
            <thead>
            <tr>
                <th>#</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>
                    <code>
                    <?php for ($i = 1; $i <= $count; $i++): ?>
                        <span id="<?php echo $i ?>" class="line"><?php echo $i ?><br/></span>
                    <?php endfor; ?>
                    </code>
                </td>
                <td><?php echo $source ?></td>
            </tr>
            </tbody>
        </table>
    </section>
<?php require './templates/footer.phtml'; ?>