<?php require './templates/header.phtml'; ?>
    <section class="graph">
        <?php require './templates/info.phtml'; ?>

        <?php
        function draw($arr, $depth = 0)
        {
            if($depth > get('fraction')) {
                return;
            }

            $str = '<li><span title="%1$s" class="type %1$s"></span>%2$s</li>';

            echo '<ol>';
            foreach ($arr as $func => $subCall) {
                echo sprintf($str, funcType($func), $func);

                if (empty($arr[$func])) {
                    continue;
                }

                draw($subCall, $depth+0.1);
            }
            echo '</ol>';
        }

        draw($nodes);
        ?>

    </section>
<?php require './templates/footer.phtml'; ?>