<div>
    <h2><?php echo $headers['cmd'] ?></h2>

    <p>
        <?php echo $headers['filename'] ?>
        @ <?php echo date('Y-m-d H:i:s', $headers['mtime']) ?><br/>
        <strong><?php echo $headers['count'] ?></strong> different functions called in
        <strong><?php echo round($headers['summary'] / 1000) ?></strong> milliseconds<br/>
    </p>
</div>

<ul>
    <?php if (get('op') !== 'trace'): ?>
        <li>
            <a href="?op=trace&fraction=<?php echo get('fraction') ?>&source=<?php echo get('source') ?>&hideInternals=<?php echo get('hideInternals') ?>" class="graph">Show
                Trace</a>
        </li>
    <?php endif; ?>
    <?php if (get('op') !== 'graph'): ?>
        <li>
            <a href="?op=graph&fraction=<?php echo get('fraction') ?>&source=<?php echo get('source') ?>&hideInternals=<?php echo get('hideInternals') ?>" class="graph">Show
                Graph</a>
        </li>
    <?php endif; ?>
</ul>

<div class="percentage">
    <?php foreach ($headers['types'] as $type => $value): ?>
        <span title="<?php echo $type ?> : <?php echo $value ?>%" class="<?php echo $type ?>" style="width: <?php echo $value ?>%">
                    <?php echo $type ?> : <?php echo $value ?>%
                </span>
    <?php endforeach; ?>
</div>