<?php require './templates/header.phtml'; ?>
    <section class="trace">
       <?php require './templates/info.phtml'; ?>

        <form>
            <fieldset>
                <label for="filter">Filter:</label>
                <input type="text" name="filter" id="filter"> (regex too)
            </fieldset>
        </form>

        <table>
            <thead>
            <tr>
                <th></th>
                <th><span>Function</span></th>
                <th></th>
                <th><span>Invocation Count</span></th>
                <th><span>Total Self Cost [%]</span></th>
                <th><span>Total Inclusive Cost [%]</span></th>
            </tr>
            </thead>
            <tbody>

            <?php foreach ($nodes as $func => $node): ?>
                <tr>
                    <td>
                        <span title="<?php echo $node['type'] ?>" class="type <?php echo $node['type'] ?>"></span>
                    </td>
                    <td>
                        <a href="#<?php echo $node['nr'] ?>" class="details"><?php echo $func ?></a>

                        <div id="<?php echo $node['nr'] ?>">
                            <?php if (!empty($node['subCall'])): ?>
                                <table>
                                    <thead>
                                    <tr>
                                        <th>Calls</th>
                                        <th>Count</th>
                                        <th>Total call cost [%]</th>
                                        <th></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <?php foreach ($node['subCall'] as $sFunc => $sNode): ?>
                                        <tr>
                                            <td><?php echo $sFunc ?></td>
                                            <td><?php echo $sNode['callCount'] ?></td>
                                            <td><?php echo $sNode['summedCallCost'] ?></td>
                                            <td>
                                                <a href="?op=file&amp;filename=<?php echo $sNode['filename'] ?>#<?php echo $sNode['line'] ?>" class="file"></a>
                                            </td>
                                        </tr>
                                    <?php endforeach; ?>
                                    </tbody>
                                </table>
                            <?php endif; ?>

                            <?php if (!empty($node['calledFrom'])): ?>
                                <table>
                                    <thead>
                                    <tr>
                                        <th>Called from</th>
                                        <th>Count</th>
                                        <th>Total call cost [%]</th>
                                        <th></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <?php foreach ($node['calledFrom'] as $sFunc => $sNode): ?>
                                        <tr>
                                            <td><?php echo $sFunc ?></td>
                                            <td><?php echo $sNode['callCount'] ?></td>
                                            <td><?php echo $sNode['summedCallCost'] ?></td>
                                            <td>
                                                <a href="?op=file&amp;filename=<?php echo $sNode['filename'] ?>#<?php echo $sNode['line'] ?>" class="file"></a>
                                            </td>
                                        </tr>
                                    <?php endforeach; ?>
                                    </tbody>
                                </table>
                            <?php endif; ?>
                        </div>
                    </td>
                    <td>
                        <?php if ($node['type'] !== 'internal') { ?>
                            <a href="?op=file&amp;filename=<?php echo $node['filename'] ?>#<?php echo $node['line'] ?>" class="file"></a>
                        <?php } ?>
                    </td>
                    <td><?php echo $node['invocationCount'] ?></td>
                    <td><?php echo $node['totalSelfCost'] ?></td>
                    <td><?php echo $node['totalInclusiveCost'] ?></td>
                </tr>
            <?php endforeach; ?>

            </tbody>
        </table>
    </section>

    <script type="text/javascript">
        function toggle(node) {
            var i, l, nodes = node.parentNode.querySelectorAll('table');
            for(i = 0, l = nodes.length; i < l; i++) {
                nodes[i].style.display = nodes[i].style.display == 'none' ? 'table' : 'none';
            }
        }

        var i, l, nodes = document.querySelectorAll('table a.details');
        for(i = 0, l = nodes.length; i < l; i++) {
            toggle(nodes[i]);
            nodes[i].addEventListener('click', function(evt) {
                evt.preventDefault();
                toggle(evt.target);
            });
        }
    </script>

<?php require './templates/footer.phtml'; ?>