<?php require './templates/header.phtml'; ?>
<script type="text/javascript" src="./js/jquery-1.9.1.min.js"></script>
<script type="text/javascript">
	$(document).ready(function() {
		$('table a.file, a.graph').attr('target', '_blank');

		$('table a.details').on('click', function(evt) {
			evt.preventDefault();

			var tr = $(this).closest('tr');
			if(!tr.find('table').length) {
				return;
			}

			tr.hasClass('details') ? tr.removeClass('details') : tr.addClass('details');
		});

		$("input[name=filter]").keyup(function() {
			var reg = new RegExp($(this).val(), 'i');
			var row;
			$('section > table').children('tbody').children('tr').each(function() {
				row = $(this);
				if(row.find('td:eq(1) a').text().match(reg))
					row.css('display', 'table-row');
				else
					row.css('display', 'none');
			});
		});
	})
</script>

<section>
	<?php require './templates/info.phtml'; ?>

	<div>
		<?php foreach($trace['headers']['types'] as $type => $value): ?>
			<span title="<?php echo $type ?>" class="<?php echo $type ?>"
			      style="width: <?php echo $value ?>%"></span>
		<?php endforeach; ?>
	</div>

	<form>
		<fieldset>
			<label for="filter">Filter:</label>
			<input type="text" name="filter" id="filter"> (regex too)
		</fieldset>
	</form>

	<table>
		<thead>
		<tr>
			<th></th>
			<th><span>Function</span></th>
			<th></th>
			<th><span>Invocation Count</span></th>
			<th><span>Total Self Cost [%]</span></th>
			<th><span>Total Inclusive Cost [%]</span></th>
		</tr>
		</thead>
		<tbody>

		<?php foreach($trace['functions'] as $func => $node): ?>
			<tr>
				<td>
					<span title="<?php echo $node['type'] ?>" class="type <?php echo $node['type'] ?>"></span>
				</td>
				<td>
					<a href="#" class="details"><?php echo $func ?></a>

					<div id="<?php echo $node['nr'] ?>">
						<?php if(!empty($node['subCall'])): ?>
							<table>
								<thead>
								<tr>
									<th>Calls</th>
									<th>Count</th>
									<th>Total call cost [%]</th>
									<th></th>
								</tr>
								</thead>
								<tbody>
								<?php foreach($node['subCall'] as $sFunc => $sNode): ?>
									<tr>
										<td><?php echo $sFunc?></td>
										<td><?php echo $sNode['callCount']?></td>
										<td><?php echo $sNode['summedCallCost']?></td>
										<td>
											<a href="?op=file&amp;filename=<?php echo $sNode['filename'] ?>#<?php echo $sNode['line'] ?>"
											   class="file"></a></td>
									</tr>
								<?php endforeach;?>
								</tbody>
							</table>
						<?php endif; ?>

						<?php if(!empty($node['calledFrom'])): ?>
							<table>
								<thead>
								<tr>
									<th>Called from</th>
									<th>Count</th>
									<th>Total call cost [%]</th>
									<th></th>
								</tr>
								</thead>
								<tbody>
								<?php foreach($node['calledFrom'] as $sFunc => $sNode): ?>
									<tr>
										<td><?php echo $sFunc?></td>
										<td><?php echo $sNode['callCount']?></td>
										<td><?php echo $sNode['summedCallCost']?></td>
										<td>
											<a href="?op=file&amp;filename=<?php echo $sNode['filename'] ?>#<?php echo $sNode['line'] ?>"
											   class="file"></a></td>
									</tr>
								<?php endforeach;?>
								</tbody>
							</table>
						<?php endif; ?>
					</div>
				</td>
				<td><a href="?op=file&amp;filename=<?php echo $node['filename'] ?>#<?php echo $node['line'] ?>"
				       class="file"></a></td>
				<td><?php echo $node['invocationCount'] ?></td>
				<td><?php echo $node['totalSelfCost'] ?></td>
				<td><?php echo $node['totalInclusiveCost'] ?></td>
			</tr>
		<?php endforeach;?>

		</tbody>
	</table>
</section>
<?php require './templates/footer.phtml'; ?>