<?php require './templates/header.phtml'; ?>
<script type="text/javascript" src="./js/jquery-1.9.1.min.js"></script>
<script type="text/javascript" src="./js/treemap.min.js"></script>
<script type="text/javascript">
	var json = <?php echo $json; ?>

		$(document).ready(function() {
			new Treemap($('#treemap'), json);
			$('div#treemap a').attr('target', '_blank');
		});
</script>
<section>
	<?php require './templates/info.phtml'; ?>
</section>

<div id="treemap"></div>
<?php require './templates/footer.phtml'; ?>